# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(help_text='url of institution')),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'passive'), (None, 'unknown')], help_text='active or passive')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, 'resolved'), (1, 'ignored'), (0, 'started'), (None, 'unknown')], help_text='active or passive')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='field for storing photo location', max_length=256)),
                ('upload_date', models.DateTimeField(help_text='date when photo was made/uploaded')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'passive'), (None, 'unknown')], help_text='state in which our problem is currently')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('url', models.URLField(help_text='url for social group')),
            ],
        ),
        migrations.AddField(
            model_name='institutionproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Problem'),
        ),
        migrations.AddField(
            model_name='institution',
            name='problems',
            field=models.ManyToManyField(through='core.InstitutionProblem', to='core.Problem'),
        ),
    ]
