# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 14:49
from __future__ import unicode_literals

import cactusproj.utils.model_utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=cactusproj.utils.model_utils.UploadToPathAndRename('problem_images')),
        ),
    ]
