# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170514_0752'),
        ('accounts', '0006_auto_20170514_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_problems',
            field=models.ManyToManyField(through='accounts.LikedProblem', to='core.Problem'),
        ),
        migrations.AlterField(
            model_name='likedproblem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
