# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170514_0752'),
        ('accounts', '0007_auto_20170514_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproblem',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='likedproblem',
            unique_together=set([('profile', 'problem')]),
        ),
    ]
